name: Test run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: suomela/type-ratio
    steps:
      - uses: actions/checkout@v2
      - name: Test run
        run: ./run-all.sh 1000
